version = 1

test_patterns = [
  "**/tests/**",
  "**/*test*.py",
  "**/*test*.js",
  "**/*test*.ts",
  "**/*.spec.ts",
  "**/*.spec.js",
  "test_*.py"
]

exclude_patterns = [
  ".venv/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  ".git/**",
  "**/__pycache__/**",
  "*.egg-info/**",
  ".coverage",
  "coverage/**",
  "docs/_build/**",
  "*.min.js",
  "*.min.css",
  "dinoair_test_files_archive.zip"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "browser",
    "nodejs",
    "jest"
  ]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "prettier"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "standardjs"