version = 1

test_patterns = [
  "**/tests/**",
  "**/*test*.py",
  "**/*test*.js",
  "**/*test*.ts",
  "**/*.spec.ts",
  "**/*.spec.js",
  "test_*.py"
]

exclude_patterns = [
  ".venv/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  ".git/**",
  "**/__pycache__/**",
  "*.egg-info/**",
  ".coverage",
  "coverage/**",
  "docs/_build/**",
  "*.min.js",
  "*.min.css",
  "dinoair_test_files_archive.zip"
]

# Python analyzer - should come first
[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x"
  max_line_length = 100

# JavaScript/TypeScript analyzer for frontend
[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "browser",
    "nodejs"
  ]

# Security analyzer for secrets detection
[[analyzers]]

name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 100


# Test coverage analyzer
[[analyzers]]
name = "test-coverage"

# Python transformers
[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

# JavaScript/TypeScript transformers
[[transformers]]
name = "prettier"
