version = 1

test_patterns = [
  "tests",
  "test_results"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "prettier"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "yapf"