version = 1

# Test patterns - directories containing test files that should be analyzed but marked as tests
test_patterns = [
  "**/tests/**",
  "**/*test*.py",
  "**/*test*.js",
  "**/*test*.ts",
  "**/*.spec.ts",
  "**/*.spec.js",
  "test_*.py"
]

# Exclude patterns - files/directories that should be completely ignored
exclude_patterns = [
  ".venv/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  ".git/**",
  "**/__pycache__/**",
  "*.egg-info/**",
  ".coverage",
  "coverage/**",
  "docs/_build/**",
  "*.min.js",
  "*.min.css",
  "dinoair_test_files_archive.zip"
]

# Python analyzer for backend code
[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.11"

  # Skip specific Python files if needed
  skip_doc_coverage = [
    "migrations/**",
    "scripts/**"
  ]

# TypeScript analyzer for frontend code
[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser",
    "es2022"
  ]
  style_guide = "standard"

# Security analyzer for secrets and vulnerabilities
[[analyzers]]
name = "secrets"

# Test coverage analyzer
[[analyzers]]
name = "test-coverage"

  [analyzers.meta]
  coverage_threshold = 80

# Python code formatters and linters
[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

# JavaScript/TypeScript formatters
[[transformers]]
name = "prettier"