name: "Test Coverage Report"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest pytest-cov
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi
    
    - name: Run tests with coverage
      run: |
        python -m pytest --cov=. --cov-report=xml --cov-report=term-missing tests/ || true
    
    - name: Install DeepSource CLI
      run: |
        curl https://deepsource.io/cli | sh
    
    - name: Report coverage to DeepSource
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      run: |
        if [ -f coverage.xml ]; then
          ./bin/deepsource report --analyzer test-coverage --key python --value-file coverage.xml
        else
          echo "⚠️  No coverage.xml found"
        fi
